In [34]:
 # Import
import pandas as pd
import numpy as np
df = pd.read_csv("data/All_Data_Aldi.csv")

 # Checking values
df.shape

(464863, 8)

In [35]:
 # Checking for NULL values (Run again to test)
df.isnull().sum()

supermarket        0
prices_(£)         0
prices_unit_(£)    4
unit               4
names              0
date               0
category           0
own_brand          0
dtype: int64

In [36]:
 # Deleting NULL values
df = df.dropna()

**CHECKING** largest and smallest values

In [37]:
df.nlargest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
154143,Aldi,3.75,2343.8,kg,Heinz Cream Of Tomato Soup 4 X 400g,20240313,food_cupboard,False
154144,Aldi,3.75,2343.8,kg,Heinz Cream Of Chicken Soup 4 X 400g,20240313,food_cupboard,False
158287,Aldi,3.75,2343.8,kg,Heinz Cream Of Tomato Soup 4 X 400g,20240312,food_cupboard,False
158290,Aldi,3.75,2343.8,kg,Heinz Cream Of Chicken Soup 4 X 400g,20240312,food_cupboard,False
163802,Aldi,3.75,2343.8,kg,Heinz Cream Of Chicken Soup 4 X 400g,20240311,food_cupboard,False
164185,Aldi,3.75,2343.8,kg,Heinz Cream Of Tomato Soup 4 X 400g,20240311,food_cupboard,False
172538,Aldi,3.75,2343.8,kg,Heinz Cream Of Tomato Soup 4 X 400g,20240310,food_cupboard,False
172542,Aldi,3.75,2343.8,kg,Heinz Cream Of Chicken Soup 4 X 400g,20240310,food_cupboard,False
175924,Aldi,3.75,2343.8,kg,Heinz Cream Of Tomato Soup 4 X 400g,20240309,food_cupboard,False
175928,Aldi,3.75,2343.8,kg,Heinz Cream Of Chicken Soup 4 X 400g,20240309,food_cupboard,False

In [38]:
df.nsmallest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
1802,Aldi,1.79,0.0,unit,Saxon Standard Toilet Tissue 4 Rolls,20240413,household,False
1803,Aldi,2.69,0.0,unit,Saxon Quilted Toilet Tissue 4 Pack,20240413,household,False
1804,Aldi,4.99,0.0,unit,Saxon Softest Premium Toilet Tissue 12 Rolls,20240413,household,False
1805,Aldi,5.29,0.0,unit,Saxon Softest Aloe Vera Toilet Tissue 8 Rolls,20240413,household,False
1806,Aldi,1.29,0.0,unit,Saxon Luxury Toilet Tissue 2 Rolls,20240413,household,False
1807,Aldi,5.29,0.0,unit,Saxon Quilted Toilet Tissue 8 Pack,20240413,household,False
1808,Aldi,2.69,0.0,unit,Saxon Softest Aloe Vera Toilet Tissue 4 Pack,20240413,household,False
1809,Aldi,2.69,0.0,unit,Saxon Softest Coconut Oil Toilet Tissue 4 Pack,20240413,household,False
1810,Aldi,4.99,0.0,unit,Saxon Softest Premium Toilet Tissue 24 Rolls,20240413,household,False
1811,Aldi,2.55,0.0,unit,Saxon Luxury Toilet Tissue 4 Rolls,20240413,household,False

In [39]:
 #Quick anomaly check
df["prices_unit_(£)"].describe()

count    464859.000000
mean          7.993101
std          41.288759
min           0.000000
25%           2.230000
50%           5.300000
75%           9.000000
max        2343.800000
Name: prices_unit_(£), dtype: float64

**CLEANING DATA**

In [40]:
# REMOVING values below 0

df = df[(df["prices_(£)"] > 0)]

FILTERING PRICES above/ below 50%

In [41]:
# Sorting values and getting previous product price
df = df.sort_values(["names", "date"])

df["previous_price"] = df.groupby("names")["prices_(£)"].shift(1)

df["previous_price"]

380250     NaN
380388     NaN
378689     NaN
378547     NaN
378975     NaN
          ...
25035     1.19
16971     1.19
13010     1.19
5854      1.19
3612      1.19
Name: previous_price, Length: 464859, dtype: float64

In [42]:
# Price change calculator (Percentage)

df["price_change"] = df["prices_(£)"] - df["previous_price"]

df["percent_change"] = (
    (df["prices_(£)"] - df["previous_price"])
    / df["previous_price"]
) * 100

df.sort_values(by="percent_change", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
68632,Aldi,0.89,3.60,kg,Bramwells Bacon Mayonnaise 250ml,20240331,food_cupboard,False,0.01,0.88,8800.000000
32631,Aldi,0.89,3.60,kg,Bramwells Lemon & Black Pepper Mayo 250ml,20240407,food_cupboard,False,0.01,0.88,8800.000000
9652,Aldi,383.00,806.32,kg,Ashfields 100% British Lamb Mince 475g,20240412,fresh_food,False,4.39,378.61,8624.373576
65308,Aldi,1.39,0.70,kg,Nature's Pick Potatoes 2kg,20240401,fresh_food,False,0.15,1.24,826.666667
67725,Aldi,2.15,7.40,l,Specially Selected Raspberry Lollies 4x73ml,20240331,frozen,True,0.29,1.86,641.379310
...,...,...,...,...,...,...,...,...,...,...,...
36431,Aldi,0.65,1.30,l,Älska Cherry Premium Cider 500ml,20240406,free-from,False,NaN,NaN,NaN
215445,Aldi,0.99,3.00,l,Älska Limited Edition Blueberry Lemonade Premi...,20240301,drinks,False,NaN,NaN,NaN
381043,Aldi,1.49,3.39,l,Älska Nordic Berries Premium Swedish Cider 440ml,20240126,drinks,False,NaN,NaN,NaN
376458,Aldi,1.49,3.39,l,Älska Strawberry & Lime Premium Swedish Cider ...,20240126,drinks,False,NaN,NaN,NaN
460969,Aldi,1.19,2.38,l,Älska The Swedish Cider Strawberry & Lime 500ml,20240109,drinks,False,NaN,NaN,NaN

In [43]:
 # Checking for NA values 
 df.isnull().sum()

supermarket           0
prices_(£)            0
prices_unit_(£)       0
unit                  0
names                 0
date                  0
category              0
own_brand             0
previous_price     7261
price_change       7261
percent_change     7261
dtype: int64

In [44]:
 #Dropping NA values again
df = df.dropna()

In [45]:
 # Finding suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

suspicious.sort_values(by='percent_change', ascending=True)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
102701,Aldi,0.01,0.00,l,Bramwells Lemon & Black Pepper Mayo 250ml,20240325,food_cupboard,False,0.19,-0.18,-94.736842
102253,Aldi,0.01,0.00,l,Bramwells Bacon Mayonnaise 250ml,20240325,food_cupboard,False,0.19,-0.18,-94.736842
97575,Aldi,0.15,0.08,kg,Nature's Pick Potatoes 2kg,20240326,fresh_food,False,1.39,-1.24,-89.208633
64962,Aldi,0.49,5.80,kg,Dairyfine Strawberry Flavour & White Choco Lun...,20240401,food_cupboard,False,2.99,-2.50,-83.612040
64969,Aldi,0.49,5.80,kg,Dairyfine Orange Choco Bertie The Bunny 85g,20240401,food_cupboard,False,2.99,-2.50,-83.612040
...,...,...,...,...,...,...,...,...,...,...,...
67726,Aldi,2.15,7.40,l,Specially Selected Coconut Lollies 4x73ml,20240331,frozen,True,0.29,1.86,641.379310
65308,Aldi,1.39,0.70,kg,Nature's Pick Potatoes 2kg,20240401,fresh_food,False,0.15,1.24,826.666667
9652,Aldi,383.00,806.32,kg,Ashfields 100% British Lamb Mince 475g,20240412,fresh_food,False,4.39,378.61,8624.373576
32631,Aldi,0.89,3.60,kg,Bramwells Lemon & Black Pepper Mayo 250ml,20240407,food_cupboard,False,0.01,0.88,8800.000000
68632,Aldi,0.89,3.60,kg,Bramwells Bacon Mayonnaise 250ml,20240331,food_cupboard,False,0.01,0.88,8800.000000

In [46]:
df.shape #quick check

(457598, 11)

In [47]:
 # REMOVING suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

df = df[df["percent_change"].abs() <= 50]

In [48]:
df.shape #quick result check

(457305, 11)

**REMOVING** prices_unit

In [49]:
  # Defining the medium
df["median_price_unit"] = (
    df.groupby("names")["prices_unit_(£)"]
      .transform("median")
)

 # Finding the % of medium 
df["percent_difference"] = (
    abs(df["prices_unit_(£)"] - df["median_price_unit"])
    / df["median_price_unit"]
) * 100

suspicious2 = df[df["percent_difference"] > 100]

suspicious2.sort_values("percent_difference", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,median_price_unit,percent_difference
459038,Aldi,1.05,2.10,kg,Earls Crunchies 500g,20240110,pets,False,1.05,0.0,0.0,0.00,inf
98510,Aldi,0.95,1.90,kg,Earls Crunchies 500g,20240326,pets,False,0.95,0.0,0.0,0.00,inf
93983,Aldi,0.95,1.90,kg,Earls Crunchies 500g,20240327,pets,False,0.95,0.0,0.0,0.00,inf
83967,Aldi,0.95,1.90,kg,Earls Crunchies 500g,20240328,pets,False,0.95,0.0,0.0,0.00,inf
81699,Aldi,0.95,1.90,kg,Earls Crunchies 500g,20240329,pets,False,0.95,0.0,0.0,0.00,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52055,Aldi,19.99,26.59,l,Louis Chevallier Chablis 75cl,20240403,drinks,False,19.99,0.0,0.0,13.29,100.075245
50764,Aldi,19.99,26.59,l,Saint Emilion Grand Cru Chateau Guillemin La G...,20240404,drinks,False,19.99,0.0,0.0,13.29,100.075245
52056,Aldi,19.99,26.59,l,Saint Emilion Grand Cru Chateau Guillemin La G...,20240403,drinks,False,19.99,0.0,0.0,13.29,100.075245
60993,Aldi,19.99,26.59,l,Saint Emilion Grand Cru Chateau Guillemin La G...,20240402,drinks,False,19.99,0.0,0.0,13.29,100.075245
60992,Aldi,19.99,26.59,l,Louis Chevallier Chablis 75cl,20240402,drinks,False,19.99,0.0,0.0,13.29,100.075245

In [50]:
 # Removes values above 100
df = df[df["percent_difference"] <= 100]

In [51]:
 # Quick anomaly check
df.nlargest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,median_price_unit,percent_difference
210591,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240302,fresh_food,True,35.23,0.0,0.0,14.99,0.0
208796,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240303,fresh_food,True,35.23,0.0,0.0,14.99,0.0
199931,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240304,fresh_food,True,35.23,0.0,0.0,14.99,0.0
195920,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240305,fresh_food,True,35.23,0.0,0.0,14.99,0.0
191611,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240306,fresh_food,True,35.23,0.0,0.0,14.99,0.0
188439,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240307,fresh_food,True,35.23,0.0,0.0,14.99,0.0
181287,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240308,fresh_food,True,35.23,0.0,0.0,14.99,0.0
174561,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240309,fresh_food,True,35.23,0.0,0.0,14.99,0.0
170834,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240310,fresh_food,True,35.23,0.0,0.0,14.99,0.0
165957,Aldi,35.23,14.99,kg,Specially Selected 2 Bone Rib Of Beef With Sea...,20240311,fresh_food,True,35.23,0.0,0.0,14.99,0.0

**REMOVING** 0.0 values

In [52]:
df.shape #quick check

(452737, 13)

In [53]:
 #Removing values
df = df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

In [54]:
df.shape #quick check

(440662, 13)

FINAL CHECK FOR ANOMALIES

In [55]:
df.nsmallest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,median_price_unit,percent_difference
460062,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240110,health_products,False,3.5,0.0,0.0,0.11,0.0
452062,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240111,health_products,False,3.5,0.0,0.0,0.11,0.0
447885,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240112,health_products,False,3.5,0.0,0.0,0.11,0.0
443000,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240113,health_products,False,3.5,0.0,0.0,0.11,0.0
438363,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240114,health_products,False,3.5,0.0,0.0,0.11,0.0
433144,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240115,health_products,False,3.5,0.0,0.0,0.11,0.0
427865,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240116,health_products,False,3.5,0.0,0.0,0.11,0.0
422294,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240117,health_products,False,3.5,0.0,0.0,0.11,0.0
403510,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240121,health_products,False,3.5,0.0,0.0,0.11,0.0
399915,Aldi,3.5,0.11,unit,Always Ultra Day Sanitary Towels Normal (Size ...,20240122,health_products,False,3.5,0.0,0.0,0.11,0.0

In [56]:
df.nlargest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,median_price_unit,percent_difference
455789,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240110,household,False,1.99,0.0,0.0,99.5,0.0
454572,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240111,household,False,1.99,0.0,0.0,99.5,0.0
449417,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240112,household,False,1.99,0.0,0.0,99.5,0.0
444477,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240113,household,False,1.99,0.0,0.0,99.5,0.0
439841,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240114,household,False,1.99,0.0,0.0,99.5,0.0
435134,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240115,household,False,1.99,0.0,0.0,99.5,0.0
429722,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240116,household,False,1.99,0.0,0.0,99.5,0.0
425406,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240117,household,False,1.99,0.0,0.0,99.5,0.0
420385,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240118,household,False,1.99,0.0,0.0,99.5,0.0
410914,Aldi,1.99,99.5,l,Scentcerity Fresh Linen And Freesia Plug-in Re...,20240119,household,False,1.99,0.0,0.0,99.5,0.0

In [57]:
 # Random results test

temp_result = df.iloc[np.random.default_rng().choice(len(df), size=5, replace=False)]

temp_result

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,median_price_unit,percent_difference
146660,Aldi,0.59,5.90,kg,Mamia Summer Fruits Jelly Pouches 4x100g,20240316,baby_products,False,0.59,0.0,0.0,5.90,0.000000
407500,Aldi,0.89,0.89,unit,Nature's Pick Pomegranate Each,20240120,fresh_food,False,0.89,0.0,0.0,0.95,6.315789
437662,Aldi,0.95,1.30,kg,Brooklea Berry Medley Low Fat Yogurts 6x125g,20240114,fresh_food,False,0.95,0.0,0.0,1.20,8.333333
170637,Aldi,3.99,21.57,kg,The Fishmonger Hot Smoked Sweet Chilli Salmon ...,20240310,fresh_food,False,3.99,0.0,0.0,21.57,0.000000
161467,Aldi,2.19,8.76,kg,Specially Selected Tomato & Burrata Ravioli 250g,20240312,fresh_food,True,2.19,0.0,0.0,8.76,0.000000

REMOVING CATEGORY

In [ ]:
final_df = df.drop(df[df['category'] == 'free-from'].index)

print(f"Original rows: {len(df)}")
print(f"Final rows: {len(final_df)}")
print(f"Rows removed: {len(df) - len(final_df)}")

CLEANUP

In [59]:
 # Renaming column
final_df = final_df.rename(columns={
    'names': 'product',
    'prices_(£)': 'prices',
    'prices_unit_(£)': 'prices_unit'
})

In [60]:
 # Dropping unecessary columns
final_df = final_df.drop(columns=['previous_price', 'price_change', 'percent_change', 'median_price_unit','percent_difference'])

In [61]:
 # Organizing Column order
final_df = final_df[['category', 'prices', 'prices_unit', 'unit', 'product', 'date', 'own_brand', 'supermarket']]

In [62]:
 # Quick column check
print(final_df.columns)

Index(['category', 'prices', 'prices_unit', 'unit', 'product', 'date',
       'own_brand', 'supermarket'],
      dtype='str')

CONVERT TO CSV

In [63]:
final_df.to_csv("Aldi_clean.csv", index=False)

In [64]:
 # Final check, vs_code database loaded properly
final_df.shape

(435655, 8)