In [1]:
 # Import
import pandas as pd
import numpy as np
df = pd.read_csv("data\All_Data_Tesco.csv")

 # Checking values
df.shape

<>:4: SyntaxWarning: invalid escape sequence '\A'
<>:4: SyntaxWarning: invalid escape sequence '\A'
C:\Users\garet\AppData\Local\Temp\ipykernel_19544\4052824024.py:4: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("data\All_Data_Tesco.csv")

(2213611, 8)

In [2]:
 # Checking for NULL values (Run again to test)
df.isnull().sum()

supermarket        0
prices_(£)         0
prices_unit_(£)    2
unit               2
names              0
date               0
category           0
own_brand          0
dtype: int64

In [3]:
 # Deleting NULL values
 df = df.dropna()

**CHECKING** largest/ smallest value

In [4]:
df.nsmallest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
771049,Tesco,0.00,0.0,kg,Tahira Chicken Smoked Sausages Hot Dogs 500G,20240311,food_cupboard,False
281063,Tesco,0.01,0.0,kg,itsu classic prawn gyoza 240g,20240402,frozen,False
697109,Tesco,0.03,0.0,unit,Dr Oetker Wafer Flowers 40'S,20240315,food_cupboard,False
697154,Tesco,0.04,0.0,unit,Dettol Protect 24 Hour Antibacterial Wipes Oce...,20240315,household,False
306912,Tesco,0.06,0.0,l,Coca-Cola Zero Sugar Lemon Coke Soft Drink 2 L...,20240401,drinks,False
332321,Tesco,0.06,0.0,l,Coca-Cola Zero Sugar Lemon Coke Soft Drink 2 L...,20240331,drinks,False
50802,Tesco,0.07,0.0,l,Tymbark Apple Watermelon Drink 2 Litre,20240411,drinks,False
230251,Tesco,0.07,0.0,unit,Ecoegg Laundry Egg Refill Pellets Fresh Linen 50S,20240404,household,False
574997,Tesco,0.07,0.0,l,Volvic Touch of Fruit Summer Fruits Still Flav...,20240320,drinks,False
598721,Tesco,0.07,0.0,l,Rubicon Sparkling Zero Added Sugar Mango 2 Litre,20240319,drinks,False

In [5]:
df.nlargest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
520040,Tesco,421.05,110803.50,l,Scholl Fungal Nail Treatment Foot Care,20240324,health_products,False
469450,Tesco,373.33,12444.42,l,GARNIER Ambre solaire SPF 50+ invisible super ...,20240326,health_products,False
23910,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240413,health_products,False
49564,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240412,health_products,False
75300,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240411,health_products,False
101036,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240410,health_products,False
126682,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240409,health_products,False
140977,Tesco,160.00,160.00,unit,Oral-B Io3 Matte Black Electric Toothbrush Plu...,20240408,health_products,False
152334,Tesco,160.00,80.00,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240408,health_products,False
166649,Tesco,160.00,160.00,unit,Oral-B Io3 Matte Black Electric Toothbrush Plu...,20240407,health_products,False

In [6]:
 #Quick anomaly check
 df["prices_unit_(£)"].describe()

count    2.213609e+06
mean     3.642805e+01
std      2.582106e+02
min      0.000000e+00
25%      3.330000e+00
50%      8.000000e+00
75%      1.625000e+01
max      1.500000e+05
Name: prices_unit_(£), dtype: float64

**CLEANING DATA**

In [7]:
# REMOVING prices 0 or below

df = df[(df["prices_(£)"] > 0)]

FILTERING PRICES above/ below 50%

In [8]:
# Sorting values and getting previous product price
df = df.sort_values(["names", "date"])

df["previous_price"] = df.groupby("names")["prices_(£)"].shift(1)

df["previous_price"]

2209625    NaN
2186593    2.0
2160774    2.0
2136166    2.0
2112122    2.0
          ...
123013     5.0
97382      5.0
71650      5.0
45900      5.0
20417      5.0
Name: previous_price, Length: 2213608, dtype: float64

In [9]:
# Price change calculator (Percentage)

df["price_change"] = df["prices_(£)"] - df["previous_price"]

df["percent_change"] = (
    (df["prices_(£)"] - df["previous_price"])
    / df["previous_price"]
) * 100

df.sort_values(by="percent_change", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
255586,Tesco,3.50,0.02,kg,itsu classic prawn gyoza 240g,20240403,frozen,False,0.01,3.49,34900.000000
140128,Tesco,100.00,16666.25,kg,Kiddylicious Banana & Pumpkin Melty Buttons 6g,20240408,baby_products,False,0.60,99.40,16566.666667
244013,Tesco,111.11,12345.27,l,Oceansaver Surface Cleaner Pnk/Grft 9Ml,20240404,household,False,1.00,110.11,11011.000000
1189185,Tesco,150.00,150000.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240223,food_cupboard,False,1.50,148.50,9900.000000
1020657,Tesco,150.00,150000.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240301,food_cupboard,False,1.50,148.50,9900.000000
...,...,...,...,...,...,...,...,...,...,...,...
2208369,Tesco,1.00,1.00,unit,"£100,000 Red Scratchcards",20240109,home,False,NaN,NaN,NaN
2203524,Tesco,5.00,5.00,unit,£2 MILLION BLACK Scratchcard,20240109,home,False,NaN,NaN,NaN
2209487,Tesco,2.00,2.00,unit,"£250,000 GOLD Scratchcard",20240109,home,False,NaN,NaN,NaN
244334,Tesco,2.00,2.00,unit,"£250,000 ORANGE Scratchcard",20240404,home,False,NaN,NaN,NaN
2202523,Tesco,5.00,5.00,unit,£50 MILLION CASH SHOWDOWN Scratchcard,20240109,home,False,NaN,NaN,NaN

In [10]:
 # Checking for NA values 
 df.isnull().sum()

supermarket            0
prices_(£)             0
prices_unit_(£)        0
unit                   0
names                  0
date                   0
category               0
own_brand              0
previous_price     30637
price_change       30637
percent_change     30637
dtype: int64

In [11]:
 #Dropping NA values again
df = df.dropna()

In [12]:
 # Finding suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

 # Displaying suspicious values
suspicious.sort_values(by='percent_change', ascending=True)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
281063,Tesco,0.01,0.00,kg,itsu classic prawn gyoza 240g,20240402,frozen,False,3.50,-3.49,-99.714286
114473,Tesco,0.60,100.00,kg,Kiddylicious Banana & Pumpkin Melty Buttons 6g,20240409,baby_products,False,100.00,-99.40,-99.400000
218402,Tesco,1.00,111.11,l,Oceansaver Surface Cleaner Pnk/Grft 9Ml,20240405,household,False,111.11,-110.11,-99.099991
997621,Tesco,1.50,1500.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240302,food_cupboard,False,150.00,-148.50,-99.000000
1164328,Tesco,1.50,1500.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240224,food_cupboard,False,150.00,-148.50,-99.000000
...,...,...,...,...,...,...,...,...,...,...,...
1189185,Tesco,150.00,150000.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240223,food_cupboard,False,1.50,148.50,9900.000000
1020657,Tesco,150.00,150000.00,kg,Lancashire Farm Whole Milk Yogurt 1Kg,20240301,food_cupboard,False,1.50,148.50,9900.000000
244013,Tesco,111.11,12345.27,l,Oceansaver Surface Cleaner Pnk/Grft 9Ml,20240404,household,False,1.00,110.11,11011.000000
140128,Tesco,100.00,16666.25,kg,Kiddylicious Banana & Pumpkin Melty Buttons 6g,20240408,baby_products,False,0.60,99.40,16566.666667
255586,Tesco,3.50,0.02,kg,itsu classic prawn gyoza 240g,20240403,frozen,False,0.01,3.49,34900.000000

In [13]:
df.shape # Quick value check

(2182971, 11)

In [14]:
 # REMOVING suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

df = df[df["percent_change"].abs() <= 50]

In [15]:
df.shape # Result check

(2178903, 11)

**REMOVING** price_unit values

In [16]:
 # ADJUST PERCENTAGE CHANGE
THRESHOLD = 50 #Adjust accordingly

 # Sort data by product and date
df = df.sort_values(["names", "date"])

 # Get the previous unit price for each product
df["previous_unit_price"] = (
    df.groupby("names")["prices_unit_(£)"]
      .shift(1)
)

 # Calculate the percentage change
df["pct_change"] = (
    abs(
        (df["prices_unit_(£)"] - df["previous_unit_price"])
        / df["previous_unit_price"]
    ) * 100
)

 # Find suspicious price changes
suspicious2 = df[df["pct_change"] > THRESHOLD]

 # Show the largest changes first
suspicious2 = suspicious2.sort_values(
    by="pct_change",
    ascending=False
)

 #Display
print(f"Rows flagged: {len(suspicious2)}")
display(suspicious2)

Rows flagged: 2836

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
1847576,Tesco,1.60,600.00,kg,Boromir Malai Extra Corn Flour 1Kg,20240124,food_cupboard,False,2.00,-0.40,-20.0000,0.0,inf
2149725,Tesco,1.75,17.50,kg,Organix Animal Biscuits 100G,20240111,baby_products,False,1.75,0.00,0.0000,0.0,inf
986509,Tesco,3.45,2.30,l,Vitasoy Soya Drink 6 X 250Ml,20240302,food_cupboard,False,3.45,0.00,0.0000,0.0,inf
255963,Tesco,1.25,0.60,l,Coca-Cola Zero Sugar Lemon Coke Soft Drink 2 L...,20240403,drinks,False,1.25,0.00,0.0000,0.0,inf
917579,Tesco,3.25,0.01,unit,Andrex Supreme Quilts Toilet Tissue Standard R...,20240305,household,False,2.60,0.65,25.0000,0.0,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267359,Tesco,1.50,41.70,kg,Deliciously Ella Almond Butter & Caramel Cups 36G,20240220,food_cupboard,False,1.00,0.50,50.0000,27.8,50.0
613494,Tesco,3.00,23.10,kg,Belazu Flavour Hacks Green Chilli 130g,20240319,food_cupboard,False,2.00,1.00,50.0000,15.4,50.0
1860958,Tesco,3.00,46.20,kg,Schwartz Nadiya Punchy Rice Bowl Recipe Kit 65g,20240123,food_cupboard,False,2.00,1.00,50.0000,30.8,50.0
1857736,Tesco,3.15,9.30,kg,Gogo Squeez Yogurt Snack Strawberry 4X85g,20240123,food_cupboard,False,2.11,1.04,49.2891,6.2,50.0
1598102,Tesco,9.00,1.80,unit,Gillette Mach 3 Disposable Men's Razors 5 Pack,20240206,health_products,False,6.00,3.00,50.0000,1.2,50.0

In [17]:
 #Removing values
clean_df = df[
    (df["pct_change"] <= THRESHOLD) |
    (df["pct_change"].isna())
]

#Check results
print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

Original rows: 2178903
Clean rows: 2176067
Rows removed: 2836

In [18]:
 clean_df.isnull().sum() #Checking for NA in new clean_df

supermarket                0
prices_(£)                 0
prices_unit_(£)            0
unit                       0
names                      0
date                       0
category                   0
own_brand                  0
previous_price             0
price_change               0
percent_change             0
previous_unit_price    30427
pct_change             35064
dtype: int64

In [19]:
clean_df = clean_df.dropna() #Dropping NA in clean_df

**REMOVING** zero's and high values

In [20]:
clean_df.shape # Check values

(2141003, 13)

In [21]:
 #Removing values
clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

C:\Users\garet\AppData\Local\Temp\ipykernel_19544\1698324100.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

Original rows: 2178903
Clean rows: 2003395
Rows removed: 175508

In [22]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 2003395 entries, 2160774 to 20417
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   supermarket          str
 1   prices_(£)           float64
 2   prices_unit_(£)      float64
 3   unit                 str
 4   names                str
 5   date                 int64
 6   category             str
 7   own_brand            bool
 8   previous_price       float64
 9   price_change         float64
 10  percent_change       float64
 11  previous_unit_price  float64
 12  pct_change           float64
dtypes: bool(1), float64(7), int64(1), str(4)
memory usage: 200.6 MB

FINAL CHECK FOR ANOMALIES

In [23]:
clean_df.nsmallest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
2145948,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240111,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2126329,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240112,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2100092,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240113,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2052381,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240115,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2076209,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240115,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2030662,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240116,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
2008360,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240117,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
1983452,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240118,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
1956145,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240119,food_cupboard,False,0.1,0.0,0.0,5.6,0.0
1936356,Tesco,0.1,5.6,kg,Drumstick Chew Bar Bubblegum 18G,20240120,food_cupboard,False,0.1,0.0,0.0,5.6,0.0

In [24]:
clean_df.nlargest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
2165573,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240111,health_products,False,160.0,0.0,0.0,80.0,0.0
2137254,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240112,health_products,False,160.0,0.0,0.0,80.0,0.0
2062974,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240115,health_products,False,160.0,0.0,0.0,80.0,0.0
2086802,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240115,health_products,False,160.0,0.0,0.0,80.0,0.0
2045615,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240116,health_products,False,160.0,0.0,0.0,80.0,0.0
2021733,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240117,health_products,False,160.0,0.0,0.0,80.0,0.0
1989372,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240118,health_products,False,160.0,0.0,0.0,80.0,0.0
1950932,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240119,health_products,False,160.0,0.0,0.0,80.0,0.0
1940408,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240120,health_products,False,160.0,0.0,0.0,80.0,0.0
1916570,Tesco,160.0,80.0,unit,Oral-B Pro 3 3900 Twin Pack Electric Toothbrush,20240121,health_products,False,160.0,0.0,0.0,80.0,0.0

In [25]:
# Random Results checker
temp_result = clean_df.iloc[np.random.default_rng().choice(len(df), size=5, replace=False)]

temp_result

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
419715,Tesco,4.00,28.57,kg,Tesco Apothecary Scented Candle – Ylang Ylang ...,20240328,home,True,4.00,0.0,0.0,28.57,0.0
1213670,Tesco,7.00,2.33,unit,Finish In Wash Dishwasher Cleaner 3 Tablets,20240222,household,False,7.00,0.0,0.0,2.33,0.0
1208961,Tesco,6.50,1.62,unit,Munchkin Love A Bowls 4 Pack,20240222,baby_products,False,6.50,0.0,0.0,1.62,0.0
449740,Tesco,8.35,8.35,unit,Wilkinson Sword Intuition Complete Razor,20240327,health_products,False,8.35,0.0,0.0,8.35,0.0
338113,Tesco,1.75,10.30,kg,Pukka Chicken & Bacon Slice 170G,20240331,fresh_food,False,1.75,0.0,0.0,10.30,0.0

REMOVING CATEGORY

In [26]:
final_df = clean_df.drop(clean_df[clean_df['category'] == 'baby_products'].index)

print(f"Original rows: {len(clean_df)}")
print(f"Final rows: {len(final_df)}")
print(f"Rows removed: {len(clean_df) - len(final_df)}")

Original rows: 2003395
Final rows: 1927911
Rows removed: 75484

CLEANUP

In [27]:
 # Renaming column
final_df = final_df.rename(columns={
    'names': 'product',
    'prices_(£)': 'prices',
    'prices_unit_(£)': 'prices_unit'
})

In [28]:
 # Dropping unecessary columns
final_df = final_df.drop(columns=['previous_price', 'price_change', 'percent_change', 'previous_unit_price', 'pct_change'])

In [29]:
 # Organizing Column order
final_df = final_df[['category', 'prices', 'prices_unit', 'unit', 'product', 'date', 'own_brand', 'supermarket']]

In [30]:
print(final_df.columns)

Index(['category', 'prices', 'prices_unit', 'unit', 'product', 'date',
       'own_brand', 'supermarket'],
      dtype='str')

CONVERT

In [31]:
final_df.to_csv("Tesco_clean.csv", index=False)

In [32]:
 # Final check, vs_code database loaded properly
final_df.shape

(1927911, 8)