In [1]:
 # Import
import pandas as pd
import numpy as np
df = pd.read_csv("data\All_Data_Sains.csv")

 # Checking values
df.shape

<>:4: SyntaxWarning: invalid escape sequence '\A'
<>:4: SyntaxWarning: invalid escape sequence '\A'
C:\Users\garet\AppData\Local\Temp\ipykernel_30248\3470227131.py:4: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("data\All_Data_Sains.csv")

(2600289, 8)

In [2]:
 # Checking for NULL values (Run again to test)
df.isnull().sum()

supermarket          0
prices_(£)           0
prices_unit_(£)    209
unit               209
names                0
date                 0
category             0
own_brand            0
dtype: int64

In [3]:
 # Deleting NULL values
 df = df.dropna()

**CHECKING** largest and smallest values

In [4]:
df.nsmallest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
2339329,Sains,0.01,0.01,unit,Sainsbury's 6 Pack Bedding,20240118,fresh_food,True
2367407,Sains,0.01,0.01,unit,Sainsbury's 6 Pack Bedding,20240117,fresh_food,True
391022,Sains,0.15,0.15,kg,Sainsbury's Carrots 1kg,20240330,free-from,True
396780,Sains,0.15,0.08,kg,Sainsbury's British White Potatoes 2kg,20240330,fresh_food,True
396791,Sains,0.15,0.30,kg,Sainsbury's Parsnips 500g,20240330,fresh_food,True
412064,Sains,0.15,0.15,unit,Sainsbury's British Swede,20240330,fresh_food,True
412084,Sains,0.15,0.15,unit,Sainsbury's Savoy Cabbage,20240330,fresh_food,True
421470,Sains,0.15,0.15,kg,Sainsbury's Carrots 1kg,20240329,free-from,True
426542,Sains,0.15,0.08,kg,Sainsbury's British White Potatoes 2kg,20240329,fresh_food,True
426552,Sains,0.15,0.30,kg,Sainsbury's Parsnips 500g,20240329,fresh_food,True

In [5]:
df.nlargest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
20785,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240413,home,False
42238,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240412,home,False
66710,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240411,home,False
87113,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240410,home,False
127598,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240409,home,False
157120,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240408,home,False
183854,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240407,home,False
205703,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240406,home,False
236676,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240405,home,False
260439,Sains,190.0,190.0,unit,Kenwood Prospero+ Stand Mixer White,20240404,home,False

In [6]:
 #Quick anomaly check
 df["prices_unit_(£)"].describe()

count    2.600080e+06
mean     4.826248e+01
std      6.076002e+02
min      0.000000e+00
25%      3.900000e+00
50%      8.000000e+00
75%      1.550000e+01
max      4.000000e+04
Name: prices_unit_(£), dtype: float64

**CLEANING DATA**

In [7]:
# REMOVING prices 0 or below

df = df[(df["prices_(£)"] > 0)]

FILTERING PRICES above/ below 50%

In [8]:
# Sorting values and getting previous product price
df = df.sort_values(["names", "date"])

df["previous_price"] = df.groupby("names")["prices_(£)"].shift(1)

df["previous_price"]

2365290     NaN
2336917    3.00
85899      3.00
65496      3.00
41349      3.00
           ...
125318     2.95
82951      2.95
62554      2.95
39484      2.95
16677      2.95
Name: previous_price, Length: 2600080, dtype: float64

In [9]:
# Price change calculator (Percentage)

df["price_change"] = df["prices_(£)"] - df["previous_price"]

df["percent_change"] = (
    (df["prices_(£)"] - df["previous_price"])
    / df["previous_price"]
) * 100

df.sort_values(by="percent_change", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
369623,Sains,1.29,0.65,kg,Sainsbury's British White Potatoes 2kg,20240331,fresh_food,True,0.15,1.14,760.000000
402635,Sains,10.00,10.00,unit,Blu 2.0 Vape Device,20240330,home,False,2.00,8.00,400.000000
2080064,Sains,10.00,10.00,unit,Blu 2.0 Vape Device,20240127,household,False,2.00,8.00,400.000000
376763,Sains,0.69,0.69,unit,Sainsbury's Savoy Cabbage,20240331,fresh_food,True,0.15,0.54,360.000000
369612,Sains,0.65,0.65,kg,Sainsbury's Carrots 1kg,20240331,fresh_food,True,0.15,0.50,333.333333
...,...,...,...,...,...,...,...,...,...,...,...
2579350,Sains,3.00,42.86,kg,tails.com Inner Vitality Cold Pressed Rewards ...,20240109,pets,False,NaN,NaN,NaN
2599301,Sains,3.00,37.50,kg,tails.com Inner Vitality Superfood Bites Lamb ...,20240109,pets,False,NaN,NaN,NaN
2595008,Sains,3.00,37.50,kg,tails.com Inner Vitality Superfood Bites Salmo...,20240109,pets,False,NaN,NaN,NaN
2582493,Sains,13.00,6.50,kg,tails.com Inner Vitality with Freshly Prepared...,20240109,pets,False,NaN,NaN,NaN
2576041,Sains,2.95,2.95,unit,zPhone Order Fee,20240109,home,False,NaN,NaN,NaN

In [10]:
 # Checking for NA values 
 df.isnull().sum()

supermarket            0
prices_(£)             0
prices_unit_(£)        0
unit                   0
names                  0
date                   0
category               0
own_brand              0
previous_price     33884
price_change       33884
percent_change     33884
dtype: int64

In [11]:
 #Dropping NA values again
df = df.dropna()

In [12]:
 # Finding suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

suspicious.sort_values(by='percent_change', ascending=True)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
529354,Sains,0.15,0.08,kg,Sainsbury's British White Potatoes 2kg,20240326,fresh_food,True,1.29,-1.14,-88.372093
1619742,Sains,4.00,4.00,unit,Rio Touch Make Up Mirror,20240214,health_products,False,20.00,-16.00,-80.000000
1138589,Sains,2.00,2.00,unit,Blu 2.0 Vape Device,20240302,health_products,False,10.00,-8.00,-80.000000
529422,Sains,0.15,0.15,unit,Sainsbury's Savoy Cabbage,20240326,fresh_food,True,0.69,-0.54,-78.260870
529388,Sains,0.15,0.30,kg,Sainsbury's Parsnips 500g,20240326,fresh_food,True,0.65,-0.50,-76.923077
...,...,...,...,...,...,...,...,...,...,...,...
369633,Sains,0.65,1.30,kg,Sainsbury's Parsnips 500g,20240331,fresh_food,True,0.15,0.50,333.333333
376763,Sains,0.69,0.69,unit,Sainsbury's Savoy Cabbage,20240331,fresh_food,True,0.15,0.54,360.000000
2080064,Sains,10.00,10.00,unit,Blu 2.0 Vape Device,20240127,household,False,2.00,8.00,400.000000
402635,Sains,10.00,10.00,unit,Blu 2.0 Vape Device,20240330,home,False,2.00,8.00,400.000000
369623,Sains,1.29,0.65,kg,Sainsbury's British White Potatoes 2kg,20240331,fresh_food,True,0.15,1.14,760.000000

In [13]:
df.shape

(2566196, 11)

In [14]:
 # REMOVING suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

df = df[df["percent_change"].abs() <= 50]

In [15]:
df.shape

(2562603, 11)

**REMOVING** price_unit values

In [16]:
 # ADJUST PERCENTAGE CHANGE
THRESHOLD = 50 #Adjust accordingly

 # Sort data by product and date
df = df.sort_values(["names", "date"])

 # Get the previous unit price for each product
df["previous_unit_price"] = (
    df.groupby("names")["prices_unit_(£)"]
      .shift(1)
)

 # Calculate the percentage change
df["pct_change"] = (
    abs(
        (df["prices_unit_(£)"] - df["previous_unit_price"])
        / df["previous_unit_price"]
    ) * 100
)

 # Find suspicious price changes
suspicious2 = df[df["pct_change"] > THRESHOLD]

 # Show the largest changes first
suspicious2 = suspicious2.sort_values(
    by="pct_change",
    ascending=False
)

 #Display
print(f"Rows flagged: {len(suspicious2)}")
display(suspicious2)

Rows flagged: 4361

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
643999,Sains,3.00,0.01,kg,Goodfella’s Light & Crispy Pepperoni Pizza 252g,20240320,frozen,False,3.00,0.0,0.000000,0.0,inf
2510146,Sains,0.99,1.00,l,Sainsbury's Strawberry Milkshake 1L,20240112,drinks,True,0.99,0.0,0.000000,0.0,inf
1357872,Sains,3.00,3.00,unit,Hermesetas Mini Sweeteners x 1200’s Tablets,20240223,food_cupboard,False,3.00,0.0,0.000000,0.0,inf
1641327,Sains,3.25,0.01,unit,Andrex Supreme Quilts Toilet Roll 4 Rolls,20240213,household,False,2.85,0.4,14.035088,0.0,inf
331923,Sains,3.25,0.01,unit,Andrex Supreme Quilts Toilet Roll 4 Rolls,20240402,household,False,2.85,0.4,14.035088,0.0,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...
308238,Sains,4.50,12.90,l,Herbal Essences Aloe Moisturise Shampoo 350ml ...,20240402,health_products,False,3.00,1.5,50.000000,8.6,50.0
1644124,Sains,4.50,12.90,kg,Lizi's Indulgent Moments Caramelised Croquant ...,20240213,free-from,False,3.00,1.5,50.000000,8.6,50.0
1638593,Sains,4.50,12.90,kg,Lizi's Indulgent Moments Granola Sea Salt Fudg...,20240213,food_cupboard,False,3.00,1.5,50.000000,8.6,50.0
2190624,Sains,1.50,41.70,kg,Deliciously Ella Double Chocolate Caramel Cups...,20240123,free-from,False,1.00,0.5,50.000000,27.8,50.0
2190119,Sains,1.50,41.70,kg,Deliciously Ella Salted Almond Caramel Cups 36g,20240123,free-from,False,1.00,0.5,50.000000,27.8,50.0

In [17]:
 #Removing values
clean_df = df[
    (df["pct_change"] <= THRESHOLD) |
    (df["pct_change"].isna())
]

#Check results
print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

Original rows: 2562603
Clean rows: 2558242
Rows removed: 4361

In [18]:
 clean_df.isnull().sum() #Checking for NA in new clean_df

supermarket                0
prices_(£)                 0
prices_unit_(£)            0
unit                       0
names                      0
date                       0
category                   0
own_brand                  0
previous_price             0
price_change               0
percent_change             0
previous_unit_price    33625
pct_change             37337
dtype: int64

In [19]:
clean_df = clean_df.dropna() #Dropping NA in clean_df

**REMOVING** zero's and high values

In [20]:
clean_df.shape # Check values

(2520905, 13)

In [21]:
 #Removing values
clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

C:\Users\garet\AppData\Local\Temp\ipykernel_30248\1698324100.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

Original rows: 2562603
Clean rows: 2384146
Rows removed: 178457

FINAL CHECK FOR ANOMALIES

In [22]:
clean_df.nsmallest(10, "pct_change")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
85899,Sains,3.0,3.0,unit,10 Pack African Marigold,20240410,home,False,3.0,0.0,0.0,3.0,0.0
65496,Sains,3.0,3.0,unit,10 Pack African Marigold,20240411,home,False,3.0,0.0,0.0,3.0,0.0
41349,Sains,3.0,3.0,unit,10 Pack African Marigold,20240412,home,False,3.0,0.0,0.0,3.0,0.0
19564,Sains,3.0,3.0,unit,10 Pack African Marigold,20240413,home,False,3.0,0.0,0.0,3.0,0.0
84626,Sains,3.0,3.0,unit,10 Pack Lobelia Mixed,20240410,home,False,3.0,0.0,0.0,3.0,0.0
64224,Sains,3.0,3.0,unit,10 Pack Lobelia Mixed,20240411,home,False,3.0,0.0,0.0,3.0,0.0
40459,Sains,3.0,3.0,unit,10 Pack Lobelia Mixed,20240412,home,False,3.0,0.0,0.0,3.0,0.0
18296,Sains,3.0,3.0,unit,10 Pack Lobelia Mixed,20240413,home,False,3.0,0.0,0.0,3.0,0.0
85886,Sains,3.0,3.0,unit,10 Pack Salvia,20240410,home,False,3.0,0.0,0.0,3.0,0.0
65483,Sains,3.0,3.0,unit,10 Pack Salvia,20240411,home,False,3.0,0.0,0.0,3.0,0.0

In [23]:
clean_df.nlargest(10, "pct_change")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
2367584,Sains,1.50,1.50,unit,7th Heaven Superfood Blueberry Mud Mask 10g,20240117,health_products,False,1.00,0.5,50.0,1.0,50.0
1625935,Sains,5.00,5.00,unit,A Dozen Red Roses,20240214,home,False,10.00,-5.0,-50.0,10.0,50.0
531221,Sains,1.50,4.50,l,AW Root Beer 330ml,20240326,drinks,False,1.00,0.5,50.0,3.0,50.0
526630,Sains,1.00,2.00,kg,Ambrosia Devon Custard 500g,20240326,food_cupboard,False,2.00,-1.0,-50.0,4.0,50.0
1646851,Sains,3.00,3.00,kg,Ambrosia Devon Custard Carton 1kg,20240213,food_cupboard,False,2.00,1.0,50.0,2.0,50.0
526576,Sains,3.00,3.00,kg,Ambrosia Devon Custard Carton 1kg,20240326,food_cupboard,False,2.00,1.0,50.0,2.0,50.0
1643214,Sains,3.00,3.00,kg,Ambrosia Devon Custard Light Carton 1kg,20240213,food_cupboard,False,2.00,1.0,50.0,2.0,50.0
528323,Sains,3.00,3.00,kg,Ambrosia Devon Custard Light Carton 1kg,20240326,food_cupboard,False,2.00,1.0,50.0,2.0,50.0
528257,Sains,1.00,2.00,kg,Ambrosia Light Devon Custard 500g,20240326,food_cupboard,False,2.00,-1.0,-50.0,4.0,50.0
1592846,Sains,1.05,5.25,l,Aptamil 3 Growing Up Milk Ready to Feed 1+ Yea...,20240215,baby_products,False,1.05,0.0,0.0,3.5,50.0

In [25]:
# Random Results checker
temp_result = clean_df.iloc[np.random.default_rng().choice(len(df), size=5, replace=False)]

temp_result

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
345155,Sains,1.5,20.0,kg,Sainsbury's Dried Cranberries 75g,20240401,food_cupboard,True,1.5,0.0,0.0,20.0,0.0
1062387,Sains,11.0,2.5,l,St Austell Brewery Tribute Pale Ale 10x440ml,20240305,free-from,False,11.0,0.0,0.0,2.5,0.0
2528258,Sains,3.4,8.5,kg,Midas Grilling Cheese 400g,20240111,fresh_food,False,3.4,0.0,0.0,8.5,0.0
242654,Sains,8.0,1.0,unit,TENA Lady Silhouette Incontinence Pants Plus L...,20240405,health_products,False,8.0,0.0,0.0,1.0,0.0
1117717,Sains,2.0,2.0,unit,FareShare £2 Donation (Only available as part ...,20240303,food_cupboard,False,2.0,0.0,0.0,2.0,0.0

REMOVING CATEGORY

In [26]:
final_df = clean_df[
    ~clean_df["category"].isin(["baby_products", "free-from"])]

print(f"Original rows: {len(clean_df)}")
print(f"Final rows: {len(final_df)}")
print(f"Rows removed: {len(clean_df) - len(final_df)}")

Original rows: 2384146
Final rows: 2093704
Rows removed: 290442

CLEANUP

In [27]:
 # Renaming column
final_df = final_df.rename(columns={
    'names': 'product',
    'prices_(£)': 'prices',
    'prices_unit_(£)': 'prices_unit'
})

In [28]:
 # Dropping unecessary columns
final_df = final_df.drop(columns=['previous_price', 'price_change', 'percent_change', 'previous_unit_price', 'pct_change'])

In [29]:
 # Organizing Column order
final_df = final_df[['category', 'prices', 'prices_unit', 'unit', 'product', 'date', 'own_brand', 'supermarket']]

In [30]:
print(final_df.columns)

Index(['category', 'prices', 'prices_unit', 'unit', 'product', 'date',
       'own_brand', 'supermarket'],
      dtype='str')

CONVERT

In [31]:
final_df.to_csv("Sains_clean.csv", index=False)

In [32]:
 # Final check, vs_code database loaded properly
final_df.shape

(2093704, 8)