In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("data\All_Data_ASDA.csv")

<>:3: SyntaxWarning: invalid escape sequence '\A'
<>:3: SyntaxWarning: invalid escape sequence '\A'
C:\Users\garet\AppData\Local\Temp\ipykernel_18824\2178271392.py:3: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("data\All_Data_ASDA.csv")
C:\Users\garet\AppData\Local\Temp\ipykernel_18824\2178271392.py:3: DtypeWarning: Columns (0: own_brand) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data\All_Data_ASDA.csv")

In [2]:
df.isnull().sum()

supermarket          0
prices_(£)           7
prices_unit_(£)    199
unit               199
names               26
date                 0
category             0
own_brand           26
dtype: int64

In [3]:
df = df.dropna()

In [4]:
df.nsmallest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
464,ASDA,2.75,0.0,unit,Hermesetas Mini Sweeteners,20240413,drinks,False
466,ASDA,3.35,0.0,unit,Sweetex Calorie Free Sweeteners 1200 Tablets,20240413,drinks,False
467,ASDA,1.70,0.0,unit,Sweetex Calorie Free Sweeteners 600 Tablets,20240413,drinks,False
1404,ASDA,1.35,0.0,unit,Bull Brand 160 Extra Slim Non-Wrapped Filter Tips,20240413,home,False
1405,ASDA,1.35,0.0,unit,Bull Brand 165 Slim Non-Wrapped Filter Tips,20240413,home,False
1410,ASDA,1.20,0.0,unit,Swan Cut Corner Rolling Papers - Multipack,20240413,home,False
1417,ASDA,1.20,0.0,unit,Swan Slim Rolling Papers - Multipack,20240413,home,False
15718,ASDA,0.60,0.0,unit,George Home Cocktail Sticks,20240413,household,True
21622,ASDA,0.50,0.0,unit,LITTLE ANGELS by ASDA Cotton Wool Buds 200 approx,20240413,health_products,True
26516,ASDA,1.50,0.0,kg,Cypressa Black Eyed Beans,20240413,food_cupboard,False

In [5]:
df.nlargest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
6636,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 20 Brown,20240413,health_products,False
6638,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 30 Deep Brown,20240413,health_products,False
6663,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 10 Blonde,20240413,health_products,False
51986,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 30 Deep Brown,20240412,health_products,False
51995,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 20 Brown,20240412,health_products,False
52015,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 10 Blonde,20240412,health_products,False
73517,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 30 Deep Brown,20240411,health_products,False
73526,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 20 Brown,20240411,health_products,False
73544,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 10 Blonde,20240411,health_products,False
98169,ASDA,8.98,99778.0,kg,Max Factor Brow Shaper 30 Deep Brown,20240410,health_products,False

In [6]:
df["prices_unit_(£)"].describe()

count    2.456196e+06
mean     7.428160e+01
std      1.081385e+03
min      0.000000e+00
25%      3.500000e+00
50%      7.500000e+00
75%      1.600000e+01
max      9.977800e+04
Name: prices_unit_(£), dtype: float64

CLEANING DATA

In [7]:
# REMOVING values below 0

df = df[(df["prices_(£)"] >= 0)]

In [8]:
df = df.sort_values(["names", "date"])

In [9]:
df["previous_price"] = df.groupby("names")["prices_(£)"].shift(1)

In [10]:
df["previous_price"]

2441325     NaN
2416027    3.55
2391447    3.55
2366637    3.55
2340659    3.55
           ...
136181     1.50
102961     1.50
67535      1.50
44899      1.50
26211      1.50
Name: previous_price, Length: 2456196, dtype: float64

In [11]:
df["price_change"] = df["prices_(£)"] - df["previous_price"]

In [12]:
df["percent_change"] = (
    (df["prices_(£)"] - df["previous_price"])
    / df["previous_price"]
) * 100

In [13]:
df.sort_values(by="percent_change", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
1891734,ASDA,28.00,2.8,kg,Tilda Pure Basmati Rice,20240130,food_cupboard,False,1.00,27.00,2700.000000
1998647,ASDA,28.00,2.8,kg,Tilda Pure Basmati Rice,20240126,food_cupboard,False,1.00,27.00,2700.000000
2214904,ASDA,35.00,35.0,unit,George Home Champagne Flute,20240118,household,True,1.50,33.50,2233.333333
2004237,ASDA,40.00,40.0,unit,Breville VKJ142 Hot Cup,20240126,drinks,False,1.85,38.15,2062.162162
623309,ASDA,12.00,61.5,kg,Lindt Milk Chocolate Gold Bunny,20240321,food_cupboard,False,0.60,11.40,1900.000000
...,...,...,...,...,...,...,...,...,...,...,...
2442179,ASDA,1.35,7.9,kg,Ísey Skyr Blueberry,20240109,fresh_food,False,NaN,NaN,NaN
2442651,ASDA,1.35,7.9,kg,Ísey Skyr Strawberry,20240109,fresh_food,False,NaN,NaN,NaN
507081,ASDA,1.15,12.8,kg,Ísey Skyr Strawberry 90g,20240326,fresh_food,False,NaN,NaN,NaN
2441257,ASDA,1.35,7.9,kg,Ísey Skyr Vanilla,20240109,fresh_food,False,NaN,NaN,NaN
2447599,ASDA,1.65,4.1,l,Łowicz Cherry Sour Syrup 400ml,20240109,food_cupboard,False,NaN,NaN,NaN

In [14]:
df = df.dropna()

In [15]:
suspicious = df[df["percent_change"].abs() > 50]

In [16]:
suspicious.sort_values(by='percent_change', ascending=True)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
1928130,ASDA,1.00,4.0,kg,Tilda Pure Basmati Rice,20240129,food_cupboard,False,28.00,-27.00,-96.428571
2188394,ASDA,1.50,1.5,unit,George Home Champagne Flute,20240119,household,True,35.00,-33.50,-95.714286
2029421,ASDA,1.85,4.1,kg,Breville VKJ142 Hot Cup,20240125,drinks,False,40.00,-38.15,-95.375000
1974629,ASDA,0.60,60.0,kg,Lindt Milk Chocolate Gold Bunny,20240127,food_cupboard,False,12.00,-11.40,-95.000000
947086,ASDA,0.35,14.0,kg,Kenco Decaff Instant Coffee,20240308,drinks,False,6.25,-5.90,-94.400000
...,...,...,...,...,...,...,...,...,...,...,...
623309,ASDA,12.00,61.5,kg,Lindt Milk Chocolate Gold Bunny,20240321,food_cupboard,False,0.60,11.40,1900.000000
2004237,ASDA,40.00,40.0,unit,Breville VKJ142 Hot Cup,20240126,drinks,False,1.85,38.15,2062.162162
2214904,ASDA,35.00,35.0,unit,George Home Champagne Flute,20240118,household,True,1.50,33.50,2233.333333
1891734,ASDA,28.00,2.8,kg,Tilda Pure Basmati Rice,20240130,food_cupboard,False,1.00,27.00,2700.000000
1998647,ASDA,28.00,2.8,kg,Tilda Pure Basmati Rice,20240126,food_cupboard,False,1.00,27.00,2700.000000

In [17]:
suspicious = df[df["percent_change"].abs() > 50]

In [18]:
df = df[df["percent_change"].abs() <= 50]

**REMOVING** prices_unit

In [19]:
 # ADJUST PERCENTAGE CHANGE

THRESHOLD = 50

In [20]:
df = df.sort_values(["names", "date"])

In [21]:
df["previous_unit_price"] = (
    df.groupby("names")["prices_unit_(£)"]
      .shift(1)
)

In [22]:
df["pct_change"] = (
    abs(
        (df["prices_unit_(£)"] - df["previous_unit_price"])
        / df["previous_unit_price"]
    ) * 100
)

In [23]:
# Find suspicous values
suspicious2 = df[df["pct_change"] > THRESHOLD]

# Show the largest changes first
suspicious2 = suspicious2.sort_values(
    by="pct_change",
    ascending=False
)

In [24]:
 #Display
print(f"Rows flagged: {len(suspicious2)}")
display(suspicious2)

Rows flagged: 4281

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
262469,ASDA,1.85,0.01,unit,"Allinson's Fantastic Fruit Loaf with Sultanas,...",20240404,fresh_food,False,1.50,0.35,23.333333,0.0,inf
1311630,ASDA,1.85,0.01,unit,"Allinson's Fantastic Fruit Loaf with Sultanas,...",20240223,bakery,False,1.25,0.60,48.000000,0.0,inf
1789455,ASDA,1.85,0.01,unit,Allinson's Fabulous Fruit Loaf with Lemon & Poppy,20240205,fresh_food,False,1.70,0.15,8.823529,0.0,inf
262496,ASDA,1.85,0.01,unit,Allinson's Fabulous Fruit Loaf with Lemon & Poppy,20240404,fresh_food,False,1.50,0.35,23.333333,0.0,inf
2223392,ASDA,2.50,5000.00,l,Vicks Inhaler Nasal Stick,20240118,health_products,False,2.50,0.00,0.000000,2.5,199900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140384,ASDA,1.85,1.80,l,Ocean Spray Blueberry 1 Litre,20240229,drinks,False,1.25,0.60,48.000000,1.2,50.0
1327920,ASDA,7.50,20.55,kg,SlimFast Chocolate Flavour Shake,20240222,health_products,False,5.00,2.50,50.000000,13.7,50.0
1325129,ASDA,7.50,20.55,kg,SlimFast Raspberry & White Choc Flavour Shake,20240222,drinks,False,5.00,2.50,50.000000,13.7,50.0
1327914,ASDA,7.50,20.55,kg,SlimFast Strawberry Flavour Shake,20240222,health_products,False,5.00,2.50,50.000000,13.7,50.0
1837956,ASDA,2.25,21.60,kg,Knorr Organic Chicken Stock Pot,20240201,food_cupboard,False,1.50,0.75,50.000000,14.4,50.0

In [25]:
 #Removing values
clean_df = df[
    (df["pct_change"] <= THRESHOLD) |
    (df["pct_change"].isna())
]

#Check results
print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

Original rows: 2416475
Clean rows: 2412194
Rows removed: 4281

In [26]:
clean_df.isnull().sum() #Checking for NA in new clean_df

supermarket                0
prices_(£)                 0
prices_unit_(£)            0
unit                       0
names                      0
date                       0
category                   0
own_brand                  0
previous_price             0
price_change               0
percent_change             0
previous_unit_price    32451
pct_change             33557
dtype: int64

In [27]:
clean_df = clean_df.dropna() #Dropping NA in clean_df

**REMOVING** zero's and high numbers

In [28]:
clean_df.shape # Check values

(2378637, 13)

In [29]:
 #Removing values
clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

C:\Users\garet\AppData\Local\Temp\ipykernel_18824\1698324100.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

Original rows: 2416475
Clean rows: 2183812
Rows removed: 232663

FINAL CHECK FOR ANOMALIES

In [30]:
clean_df.nsmallest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
2392015,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240111,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2356732,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240112,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2348991,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240113,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2322692,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240114,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2297327,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240115,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2254091,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240116,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2233549,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240117,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2203083,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240118,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2181569,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240119,fresh_food,True,0.05,0.0,0.0,6.0,0.0
2152584,ASDA,0.05,6.0,kg,ASDA Loose Okra,20240120,fresh_food,True,0.05,0.0,0.0,6.0,0.0

In [31]:
clean_df.nlargest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
2361417,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240112,home,False,99.99,0.0,0.0,99.99,0.0
2335830,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240113,home,False,99.99,0.0,0.0,99.99,0.0
2284064,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240115,home,False,99.99,0.0,0.0,99.99,0.0
2255703,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240116,home,False,99.99,0.0,0.0,99.99,0.0
2233785,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240117,home,False,99.99,0.0,0.0,99.99,0.0
2224682,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240118,home,False,99.99,0.0,0.0,99.99,0.0
2182489,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240119,home,False,99.99,0.0,0.0,99.99,0.0
2157448,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240120,home,False,99.99,0.0,0.0,99.99,0.0
2132170,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240121,home,False,99.99,0.0,0.0,99.99,0.0
2108028,ASDA,99.99,99.99,unit,Amazon Fire Hd 8 Tablet,20240122,home,False,99.99,0.0,0.0,99.99,0.0

In [32]:
clean_df.shape

(2183812, 13)

In [33]:
# Random Results checker
temp_result = clean_df.iloc[np.random.default_rng().choice(len(df), size=5, replace=False)]

temp_result

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
1593690,ASDA,1.30,1.73,l,Harpic Active Fresh Marine Splash,20240213,household,False,1.30,0.0,0.0,1.73,0.0
2018563,ASDA,1.49,1.49,kg,ASDA Caster Sugar,20240126,food_cupboard,True,1.49,0.0,0.0,1.49,0.0
1171196,ASDA,3.50,5.80,kg,Heinz Light Salad Cream,20240228,food_cupboard,False,3.50,0.0,0.0,5.80,0.0
968397,ASDA,2.50,1.25,unit,The BAKERY at ASDA 2 Sticky Toffee Puddings,20240307,fresh_food,True,2.50,0.0,0.0,1.25,0.0
1746274,ASDA,4.00,40.00,kg,L'OR Classique Instant Coffee,20240207,drinks,False,4.00,0.0,0.0,40.00,0.0

REMOVING A CATEGORY

In [35]:
final_df = clean_df[
    ~clean_df["category"].isin(["baby_products", "free-from"])]

print(f"Original rows: {len(clean_df)}")
print(f"Final rows: {len(final_df)}")
print(f"Rows removed: {len(clean_df) - len(final_df)}")

Original rows: 2183812
Final rows: 2057388
Rows removed: 126424

CLEANUP

In [36]:
 # Renaming column
final_df = final_df.rename(columns={
    'names': 'product',
    'prices_(£)': 'prices',
    'prices_unit_(£)': 'prices_unit'
})

In [37]:
 # Dropping unecessary columns
final_df = final_df.drop(columns=['previous_price', 'price_change', 'percent_change', 'previous_unit_price', 'pct_change'])

In [38]:
 # Organizing Column order
final_df = final_df[['category', 'prices', 'prices_unit', 'unit', 'product', 'date', 'own_brand', 'supermarket']]

In [39]:
print(final_df.columns)

Index(['category', 'prices', 'prices_unit', 'unit', 'product', 'date',
       'own_brand', 'supermarket'],
      dtype='str')

EXPORT

In [40]:
final_df.to_csv("Asda_clean.csv", index=False)

In [41]:
 # Final check, vs_code database loaded properly
final_df.shape

(2057388, 8)