In [1]:
 # Import
import pandas as pd
import numpy as np
df = pd.read_csv("data\All_Data_Morrisons.csv")

 # Checking values
df.shape

<>:4: SyntaxWarning: invalid escape sequence '\A'
<>:4: SyntaxWarning: invalid escape sequence '\A'
C:\Users\garet\AppData\Local\Temp\ipykernel_15428\3724043193.py:4: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("data\All_Data_Morrisons.csv")

(1794065, 8)

In [2]:
 # Checking for NULL values (Run again to test)
df.isnull().sum()

supermarket          0
prices_(£)           0
prices_unit_(£)    110
unit               110
names                0
date                 0
category             0
own_brand            0
dtype: int64

In [3]:
 # Deleting NULL values
df = df.dropna()

**CHECKING** largest and smallest values

In [4]:
df.nsmallest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
1172,Morrisons,0.70,0.0,unit,Nutmeg 200 Paper Stemmed Cotton Buds,20240413,health_products,True
3076,Morrisons,1.39,0.0,unit,Regal Hot Bombay Mix,20240413,food_cupboard,False
3181,Morrisons,1.70,0.0,kg,Proste Historie Kopytka,20240413,food_cupboard,False
7600,Morrisons,0.70,0.0,unit,Nutmeg Cotton Wool Buds,20240413,baby_products,True
9301,Morrisons,2.50,0.0,kg,Blue Dragon Chow Mein Kit,20240413,food_cupboard,False
10168,Morrisons,4.50,0.0,unit,Hermesetas,20240413,food_cupboard,False
10274,Morrisons,1.00,0.0,unit,Slimmers Calorie Free Sweeteners,20240413,food_cupboard,False
14419,Morrisons,1.50,0.0,m,Nutmeg Cream Pillar Candle Small,20240413,household,True
21192,Morrisons,2.50,0.0,kg,Blue Dragon Chow Mein Kit,20240412,food_cupboard,False
22006,Morrisons,4.50,0.0,unit,Hermesetas,20240412,food_cupboard,False

In [5]:
df.nlargest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
426323,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240320,health_products,False
446800,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240319,health_products,False
468712,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240318,health_products,False
491040,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240317,health_products,False
514953,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240316,health_products,False
537354,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240315,health_products,False
557098,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240313,health_products,False
577707,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240312,health_products,False
600259,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240311,health_products,False
625220,Morrisons,300.0,300.0,unit,Oral-B Io Series 6 Ultimate Clean…,20240310,health_products,False

In [6]:
 #Quick anomaly check
df["prices_unit_(£)"].describe()

count    1.793955e+06
mean     2.618102e+01
std      1.661642e+02
min      0.000000e+00
25%      3.300000e+00
50%      7.400000e+00
75%      1.495000e+01
max      1.122500e+04
Name: prices_unit_(£), dtype: float64

**CLEANING DATA**

In [7]:
# REMOVING values below 0

df = df[(df["prices_(£)"] > 0)]

FILTERING PRICES above/ below 50%

In [8]:
# Sorting values and getting previous product price
df = df.sort_values(["names", "date"])

df["previous_price"] = df.groupby("names")["prices_(£)"].shift(1)

df["previous_price"]

356673      NaN
352918    12.98
317442    12.98
298452    12.98
282652    12.98
          ...
63089      2.25
57441      2.25
37103      2.25
18430      2.25
1163       2.25
Name: previous_price, Length: 1793955, dtype: float64

In [9]:
# Price change calculator (Percentage)

df["price_change"] = df["prices_(£)"] - df["previous_price"]

df["percent_change"] = (
    (df["prices_(£)"] - df["previous_price"])
    / df["previous_price"]
) * 100

df.sort_values(by="percent_change", ascending=False)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
1727350,Morrisons,11.00,6.60,kg,Morrisons Spaghetti,20240112,food_cupboard,True,0.75,10.25,1366.666667
1609848,Morrisons,28.00,28.00,unit,Baylis & Harding Sweet Mandarin…,20240119,home,False,2.25,25.75,1144.444444
1682421,Morrisons,28.00,28.00,unit,Baylis & Harding Sweet Mandarin…,20240115,home,False,2.25,25.75,1144.444444
1724991,Morrisons,11.50,7.99,kg,Pedigree Dentastix Daily Adult Medium D…,20240112,pets,False,0.99,10.51,1061.616162
1653255,Morrisons,9.75,12.20,kg,SMA Little Steps First Baby M…,20240116,baby_products,False,0.85,8.90,1047.058824
...,...,...,...,...,...,...,...,...,...,...,...
1777825,Morrisons,1.25,1.70,l,evian Natural Mineral Water Sports Cap,20240109,drinks,False,NaN,NaN,NaN
1776466,Morrisons,1.90,0.08,unit,lights by TENA Incontinence Liners,20240109,health_products,False,NaN,NaN,NaN
1781430,Morrisons,3.75,0.08,unit,lights by TENA Incontinence Liners Duo,20240109,health_products,False,NaN,NaN,NaN
1776358,Morrisons,1.90,0.07,unit,lights by TENA Light Incontinence Liners,20240109,health_products,False,NaN,NaN,NaN
1775932,Morrisons,1.90,0.10,unit,lights by TENA Long Incontinence Liners,20240109,health_products,False,NaN,NaN,NaN

In [10]:
 # Checking for NA values 
 df.isnull().sum()

supermarket            0
prices_(£)             0
prices_unit_(£)        0
unit                   0
names                  0
date                   0
category               0
own_brand              0
previous_price     26181
price_change       26181
percent_change     26181
dtype: int64

In [11]:
 #Dropping NA values again
df = df.dropna()

In [12]:
 # Finding suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

suspicious.sort_values(by='percent_change', ascending=True)

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change
1705041,Morrisons,0.75,1.50,kg,Morrisons Spaghetti,20240113,food_cupboard,True,11.00,-10.25,-93.181818
1591089,Morrisons,2.25,4.50,l,Baylis & Harding Sweet Mandarin…,20240120,health_products,False,28.00,-25.75,-91.964286
1621216,Morrisons,2.25,4.50,l,Baylis & Harding Sweet Mandarin…,20240118,health_products,False,28.00,-25.75,-91.964286
1705657,Morrisons,0.99,7.70,kg,Pedigree Dentastix Daily Adult Medium D…,20240113,pets,False,11.50,-10.51,-91.391304
955407,Morrisons,0.85,4.20,l,SMA Little Steps First Baby M…,20240222,baby_products,False,9.75,-8.90,-91.282051
...,...,...,...,...,...,...,...,...,...,...,...
1653255,Morrisons,9.75,12.20,kg,SMA Little Steps First Baby M…,20240116,baby_products,False,0.85,8.90,1047.058824
1724991,Morrisons,11.50,7.99,kg,Pedigree Dentastix Daily Adult Medium D…,20240112,pets,False,0.99,10.51,1061.616162
1682421,Morrisons,28.00,28.00,unit,Baylis & Harding Sweet Mandarin…,20240115,home,False,2.25,25.75,1144.444444
1609848,Morrisons,28.00,28.00,unit,Baylis & Harding Sweet Mandarin…,20240119,home,False,2.25,25.75,1144.444444
1727350,Morrisons,11.00,6.60,kg,Morrisons Spaghetti,20240112,food_cupboard,True,0.75,10.25,1366.666667

In [13]:
df.shape #quick check

(1767774, 11)

In [14]:
 # REMOVING suspicious values 
suspicious = df[df["percent_change"].abs() > 50]

df = df[df["percent_change"].abs() <= 50]

In [15]:
df.shape #quick result check

(1759043, 11)

**REMOVING** Price_unit

In [16]:
 # ADJUST PERCENTAGE CHANGE
THRESHOLD = 50 #Adjust accordingly

 # Sort data by product and date
df = df.sort_values(["names", "date"])

 # Get the previous unit price for each product
df["previous_unit_price"] = (
    df.groupby("names")["prices_unit_(£)"]
      .shift(1)
)

 # Calculate the percentage change
df["pct_change"] = (
    abs(
        (df["prices_unit_(£)"] - df["previous_unit_price"])
        / df["previous_unit_price"]
    ) * 100
)

 # Find suspicious price changes
suspicious2 = df[df["pct_change"] > THRESHOLD]

 # Show the largest changes first
suspicious2 = suspicious2.sort_values(
    by="pct_change",
    ascending=False
)

 #Display
print(f"Rows flagged: {len(suspicious2)}")
display(suspicious2)

Rows flagged: 4781

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
1503694,Morrisons,2.25,0.01,unit,Silver Spoon Sweetener,20240125,food_cupboard,False,1.50,0.75,50.000000,0.00,inf
1729271,Morrisons,0.85,30.30,kg,Silver Spoon Sweetener,20240112,food_cupboard,False,1.50,-0.65,-43.333333,0.00,inf
1689327,Morrisons,2.49,13.83,kg,Morrisons Wensleydale & Cranberries,20240114,fresh_food,True,2.25,0.24,10.666667,0.01,138200.0
1729547,Morrisons,1.75,11.00,kg,Canderel 0 Calories,20240112,food_cupboard,False,1.65,0.10,6.060606,0.01,109900.0
184546,Morrisons,2.20,36.70,kg,Grenade Protein Bars Oreo White,20240403,health_products,False,2.20,0.00,0.000000,0.04,91650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748196,Morrisons,0.90,1.80,l,Morrisons Fresh Whole Milk,20240111,fresh_food,True,1.20,-0.30,-25.000000,1.20,50.0
40294,Morrisons,2.25,9.90,kg,Sharwood's Green Label Mango Chutney,20240411,food_cupboard,False,1.50,0.75,50.000000,6.60,50.0
1368355,Morrisons,4.20,4.20,unit,Wilkinson Sword Xtreme 3 Beauty W…,20240201,health_products,False,4.20,0.00,0.000000,2.80,50.0
1123157,Morrisons,4.49,9.90,kg,Whole Earth Original Smooth Peanut Butter,20240214,food_cupboard,False,3.00,1.49,49.666667,6.60,50.0
1123127,Morrisons,4.49,9.90,kg,Whole Earth Original Crunchy Peanut Butter,20240214,food_cupboard,False,3.00,1.49,49.666667,6.60,50.0

In [17]:
 #Removing values
clean_df = df[
    (df["pct_change"] <= THRESHOLD) |
    (df["pct_change"].isna())
]

#Check results
print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

Original rows: 1759043
Clean rows: 1754262
Rows removed: 4781

In [18]:
 clean_df.isnull().sum() #Checking for NA in new clean_df

supermarket                0
prices_(£)                 0
prices_unit_(£)            0
unit                       0
names                      0
date                       0
category                   0
own_brand                  0
previous_price             0
price_change               0
percent_change             0
previous_unit_price    25489
pct_change             26231
dtype: int64

In [19]:
clean_df = clean_df.dropna() #Dropping NA in clean_df

**REMOVING** zero's and high numbers

In [20]:
clean_df.shape # Check values

(1728031, 13)

In [21]:
 #Removing values
clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

print(f"Original rows: {len(df)}")
print(f"Clean rows: {len(clean_df)}")
print(f"Rows removed: {len(df) - len(clean_df)}")

C:\Users\garet\AppData\Local\Temp\ipykernel_15428\1698324100.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  clean_df = clean_df[(df["prices_unit_(£)"] > 0.1) & (df["prices_unit_(£)"] < 100)]

Original rows: 1759043
Clean rows: 1638907
Rows removed: 120136

FINAL CHECK FOR ANOMALIES

In [22]:
clean_df.nsmallest(10, "prices_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
404072,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240321,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
383246,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240322,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
360290,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240324,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
345641,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240325,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
326027,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240326,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
305646,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240327,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
292853,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240328,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
264527,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240329,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
246996,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240330,food_cupboard,False,0.25,0.0,0.0,13.9,0.0
238177,Morrisons,0.25,13.9,kg,Cadbury Freddo,20240331,food_cupboard,False,0.25,0.0,0.0,13.9,0.0

In [23]:
clean_df.nlargest(10, "prices_unit_(£)")

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
368806,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240324,health_products,False,4.99,0.0,0.0,99.8,0.0
349286,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240325,health_products,False,4.99,0.0,0.0,99.8,0.0
329113,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240326,health_products,False,4.99,0.0,0.0,99.8,0.0
302276,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240327,health_products,False,4.99,0.0,0.0,99.8,0.0
280819,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240328,health_products,False,4.99,0.0,0.0,99.8,0.0
275402,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240329,health_products,False,4.99,0.0,0.0,99.8,0.0
251627,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240330,health_products,False,4.99,0.0,0.0,99.8,0.0
241223,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240331,health_products,False,4.99,0.0,0.0,99.8,0.0
214979,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240401,health_products,False,4.99,0.0,0.0,99.8,0.0
200585,Morrisons,4.99,99.8,l,Malibu Scalp Protector SPF 50,20240402,health_products,False,4.99,0.0,0.0,99.8,0.0

In [24]:
clean_df.shape

(1638907, 13)

In [26]:
# Random Results checker
temp_result = clean_df.iloc[np.random.default_rng().choice(len(df), size=5, replace=False)]

temp_result

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand,previous_price,price_change,percent_change,previous_unit_price,pct_change
437202,Morrisons,1.50,5.00,kg,McCain Shake Shake Sea Salt & Cra…,20240319,fresh_food,False,1.50,0.0,0.0,5.00,0.0
1494124,Morrisons,2.39,1.60,l,Morrisons 100% Orange Juice With Bits,20240125,drinks,True,2.39,0.0,0.0,1.60,0.0
271621,Morrisons,1.30,1.73,l,Harpic Bleach White & Shine Toilet Cleaner,20240329,household,False,1.30,0.0,0.0,1.73,0.0
489664,Morrisons,2.10,16.80,kg,Lindt Classic Recipe Hazelnut Milk Chocolate,20240317,food_cupboard,False,2.10,0.0,0.0,16.80,0.0
808196,Morrisons,1.80,9.00,kg,Morrisons Dark Chocolate,20240229,food_cupboard,True,1.80,0.0,0.0,9.00,0.0

REMOVING CATEGORY

In [27]:
final_df = clean_df[
    ~clean_df["category"].isin(["baby_products", "free-from"])]

print(f"Original rows: {len(clean_df)}")
print(f"Final rows: {len(final_df)}")
print(f"Rows removed: {len(clean_df) - len(final_df)}")

Original rows: 1638907
Final rows: 1552549
Rows removed: 86358

CLEANUP

In [28]:
 # Renaming column
final_df = final_df.rename(columns={
    'names': 'product',
    'prices_(£)': 'prices',
    'prices_unit_(£)': 'prices_unit'
})

In [29]:
 # Dropping unecessary columns
final_df = final_df.drop(columns=['previous_price', 'price_change', 'percent_change', 'previous_unit_price', 'pct_change'])

In [30]:
 # Organizing Column order
final_df = final_df[['category', 'prices', 'prices_unit', 'unit', 'product', 'date', 'own_brand', 'supermarket']]

In [31]:
print(final_df.columns)

Index(['category', 'prices', 'prices_unit', 'unit', 'product', 'date',
       'own_brand', 'supermarket'],
      dtype='str')

CONVERT

In [32]:
final_df.to_csv("Morrisons_clean.csv", index=False)

In [33]:
 # Final check, vs_code database loaded properly
final_df.shape

(1552549, 8)